name: Python package

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yapf
      - name: Format with Yapf
        run: |
          yapf -r -d ./src/
